name       : python-flit-core
version    : 3.7.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/f/flit_core/flit_core-3.7.1.tar.gz : 14955af340c43035dbfa96b5ee47407e377ee337f69e70f73064940d27d0a44f
homepage   : https://github.com/pypa/flit
license    : BSD-3-Clause
component  : programming.python
summary    : Distribution-building parts of Flit
description: |
    Flit is a simple way to put Python packages and modules on PyPI. It tries to require less thought about packaging and help you avoid common mistakes.
builddeps  :
    - python-wheel
build      : |
    python3 -m pip wheel --no-deps .
install    : |
    python3 -m pip install --root=%installroot% --no-deps *.whl
