name       : python-flit-core
version    : 3.8.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/f/flit_core/flit_core-3.8.0.tar.gz : b305b30c99526df5e63d6022dd2310a0a941a187bd3884f4c8ef0418df6c39f3
homepage   : https://github.com/pypa/flit
license    : BSD-3-Clause
component  : programming.python
summary    : Distribution-building parts of Flit
description: |
    Flit is a simple way to put Python packages and modules on PyPI. It tries to require less thought about packaging and help you avoid common mistakes.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
